export const BLUE_THEME = {
  name: "BLUE_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#0085db",
    secondary: "#707a82",
    info: "#46caeb",
    success: "#4bd08b",
    warning: "#f8c076",
    error: "#fb977d",
    indigo: "#8763da",
    lightprimary: "#e5f3fb",
    lightinfo: "#e1f5fa",
    lightsecondary: "#e7ecf0",
    lightsuccess: "#dffff3",
    lighterror: "#ffede9",
    lightwarning: "#fff6ea",
    lightindigo: "#f1ebff",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f0f5f9",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    grey100: "#707a82",
    grey200: "#111c2d",
  },
};

export const AQUA_THEME = {
  name: "AQUA_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#0074BA",
    secondary: "#47D7BC",
    info: "#46caeb",
    success: "#4bd08b",
    warning: "#f8c076",
    error: "#fb977d",
    indigo: "#8763da",
    lightprimary: "#e5f3fb",
    lightinfo: "#e1f5fa",
    lightsecondary: "#e7ecf0",
    lightsuccess: "#dffff3",
    lighterror: "#ffede9",
    lightwarning: "#fff6ea",
    lightindigo: "#f1ebff",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f0f5f9",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    grey100: "#707a82",
    grey200: "#111c2d",
  },
};

export const PURPLE_THEME = {
  name: "PURPLE_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#763EBD",
    secondary: "#95CFD5",
    info: "#46caeb",
    success: "#4bd08b",
    warning: "#f8c076",
    error: "#fb977d",
    indigo: "#8763da",
    lightprimary: "#e5f3fb",
    lightinfo: "#e1f5fa",
    lightsecondary: "#e7ecf0",
    lightsuccess: "#dffff3",
    lighterror: "#ffede9",
    lightwarning: "#fff6ea",
    lightindigo: "#f1ebff",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f0f5f9",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    grey100: "#707a82",
    grey200: "#111c2d",
  },
};

export const GREEN_THEME = {
  name: "GREEN_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#0A7EA4",
    secondary: "#CCDA4E",
    info: "#46caeb",
    success: "#4bd08b",
    warning: "#f8c076",
    error: "#fb977d",
    indigo: "#8763da",
    lightprimary: "#e5f3fb",
    lightinfo: "#e1f5fa",
    lightsecondary: "#e7ecf0",
    lightsuccess: "#dffff3",
    lighterror: "#ffede9",
    lightwarning: "#fff6ea",
    lightindigo: "#f1ebff",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f0f5f9",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    grey100: "#707a82",
    grey200: "#111c2d",
  },
};

export const CYAN_THEME = {
  name: "CYAN_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#01C0C8",
    secondary: "#FB9678",
    info: "#46caeb",
    success: "#4bd08b",
    warning: "#f8c076",
    error: "#fb977d",
    indigo: "#8763da",
    lightprimary: "#e5f3fb",
    lightinfo: "#e1f5fa",
    lightsecondary: "#e7ecf0",
    lightsuccess: "#dffff3",
    lighterror: "#ffede9",
    lightwarning: "#fff6ea",
    lightindigo: "#f1ebff",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f0f5f9",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    grey100: "#707a82",
    grey200: "#111c2d",
  },
};

export const ORANGE_THEME = {
  name: "ORANGE_THEME",
  dark: false,
  variables: {
    "border-color": "#e5eaef",
  },
  colors: {
    primary: "#FA896B",
    secondary: "#0074BA",
    info: "#46caeb",
    success: "#4bd08b",
    warning: "#f8c076",
    error: "#fb977d",
    indigo: "#8763da",
    lightprimary: "#e5f3fb",
    lightinfo: "#e1f5fa",
    lightsecondary: "#e7ecf0",
    lightsuccess: "#dffff3",
    lighterror: "#ffede9",
    lightwarning: "#fff6ea",
    lightindigo: "#f1ebff",
    textPrimary: "#2A3547",
    textSecondary: "#2A3547",
    borderColor: "#e5eaef",
    inputBorder: "#DFE5EF",
    containerBg: "#ffffff",
    background: "#f0f5f9",
    hoverColor: "#f6f9fc",
    surface: "#fff",
    grey100: "#707a82",
    grey200: "#111c2d",
  },
};

// Default light theme export
export const LightTheme = BLUE_THEME;

// Dark theme
export const DarkTheme = {
  name: "DarkTheme",
  dark: true,
  variables: {
    "border-color": "#333F55",
  },
  colors: {
    primary: "#0085db",
    secondary: "#707a82",
    info: "#46caeb",
    success: "#4bd08b",
    warning: "#f8c076",
    error: "#fb977d",
    indigo: "#8763da",
    lightprimary: "#1c3a5a",
    lightinfo: "#1a3e4a",
    lightsecondary: "#2a3540",
    lightsuccess: "#1e4a3a",
    lighterror: "#4a2a2a",
    lightwarning: "#4a3a2a",
    lightindigo: "#3a2a4a",
    textPrimary: "#eaeff4",
    textSecondary: "#adb0bb",
    borderColor: "#333F55",
    inputBorder: "#465670",
    containerBg: "#171c23",
    background: "#0f1419",
    hoverColor: "#1c2128",
    surface: "#171c23",
    grey100: "#adb0bb",
    grey200: "#eaeff4",
  },
};
